# GitHub Pages Configuration for Property Valuation ML System

# Theme settings
theme: jekyll-theme-minimal
title: Property Valuation ML System
description: A professional machine learning system for real estate property valuation in the Chilean market

# Enable GitHub Flavored Markdown
markdown: GFM

# Custom CSS
sass:
  sass_dir: assets/css
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Default layout
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Site settings
url: "https://username.github.io/property-valuation"
baseurl: "/property-valuation"
repository: "username/property-valuation"

# Navigation
header_pages:
  - getting-started.md
  - installation-guide.md
  - user-manual.md
  - api-documentation.md
  - github-pages-deployment.md
  - Challenge.md
